#pragma once
#include <fstream>

namespace pkmn
{
	//Pokemon Types
	enum Type
	{
		NORMAL, FIRE, WATER, GRASS, ELECTRIC, ICE,
		FIGHTING, POISON, GROUND, FLYING, PSYCHIC, BUG,
		ROCK, GHOST, DRAGON, DARK, STEEL, FAIRY
	};
	const std::string TYPE_NAMES[] =
	{
		"Normal", "Fire", "Water", "Grass", "Electric", "Ice",
		"Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug",
		"Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"
	};
	const int NUM_TYPES = 18;
	
	//Pokemon Statistics
	enum Stat 
	{ 
		HP, ATK, DEF, 
		SPATK, SPDEF, SPEED
	};
	const std::string STAT_NAMES[] = 
	{
		"HP", "Attack", "Defense", 
		"Special Attack", "Special Defense", "Speed"
	};

	const int NUM_STATS = 6;

	//Maximum values
	const int MAX_TYPES = 2;
	const int MAX_MOVES = 4;
	const int MAX_PARTY = 6;
	const int STAT_DELTA = 6;
	const int MAX_IV = 31;
	const int MAX_EV = 255;

	//Because this is initialized by a file, I don't really know how to stop the warnings generated by it
	//The first dimension represents the attacking type
	//The second dimension represents the defending type
	static double typeModifiers[NUM_TYPES][NUM_TYPES] = {};

	void setTypeModifiers(std::ifstream& file);
}
